/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Translational_drone_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[8] = {0, 1, 2, 6, 9, 12, 15, 19};
static const casadi_int casadi_s1[6] = {3, 10, 13, 16, 20, 23};
static const casadi_int casadi_s2[6] = {4, 7, 14, 17, 21, 24};
static const casadi_int casadi_s3[5] = {5, 8, 11, 18, 22};
static const casadi_int casadi_s4[38] = {10, 10, 0, 0, 0, 0, 5, 11, 17, 22, 23, 24, 25, 4, 5, 6, 7, 8, 3, 5, 6, 7, 8, 9, 3, 4, 6, 7, 8, 9, 3, 4, 5, 7, 8, 0, 1, 2};
static const casadi_int casadi_s5[38] = {10, 10, 0, 1, 2, 3, 6, 9, 12, 15, 19, 23, 25, 7, 8, 9, 4, 5, 6, 3, 5, 6, 3, 4, 6, 3, 4, 5, 3, 4, 5, 6, 3, 4, 5, 6, 4, 5};
static const casadi_int casadi_s6[23] = {10, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s7[7] = {0, 3, 6, 9, 12, 13, 14};
static const casadi_int casadi_s8[22] = {10, 4, 0, 3, 7, 11, 15, 7, 8, 9, 3, 4, 5, 6, 3, 4, 5, 6, 3, 4, 5, 6};
static const casadi_int casadi_s9[28] = {4, 10, 0, 0, 0, 0, 3, 6, 9, 12, 13, 14, 15, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s10[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s11[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s12[3] = {0, 0, 0};
static const casadi_int casadi_s13[3] = {10, 0, 0};

/* Translational_drone_impl_dae_jac_x_xdot_u_z:(i0[10],i1[10],i2[4],i3[],i4[])->(o0[10x10,25nz],o1[10x10,10nz],o2[10x4,15nz],o3[10x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real *w0=w+0, *w1=w+25, w2, w3, w4, w5, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, *w25=w+53, *w26=w+61, w29, w30, w31, w32, w33, *w34=w+74, *w35=w+80, w36, *w38=w+87, *w39=w+92, *w40=w+97, *w41=w+122, *w42=w+132, *w43=w+142, *w44=w+157, *w45=w+159, *w47=w+166, *w48=w+170, *w49=w+174;
  /* #0: @0 = zeros(10x10,25nz) */
  casadi_clear(w0, 25);
  /* #1: @1 = ones(10x1,7nz) */
  casadi_fill(w1, 7, 1.);
  /* #2: {NULL, NULL, NULL, @2, NULL, NULL, NULL, @3, @4, @5} = vertsplit(@1) */
  w2 = w1[3];
  w3 = w1[4];
  w4 = w1[5];
  w5 = w1[6];
  /* #3: @6 = 00 */
  /* #4: @7 = 0.5 */
  w7 = 5.0000000000000000e-01;
  /* #5: @8 = input[2][1] */
  w8 = arg[2] ? arg[2][1] : 0;
  /* #6: @9 = (@8*@2) */
  w9  = (w8*w2);
  /* #7: @9 = (@7*@9) */
  w9  = (w7*w9);
  /* #8: @10 = 0.5 */
  w10 = 5.0000000000000000e-01;
  /* #9: @11 = input[2][2] */
  w11 = arg[2] ? arg[2][2] : 0;
  /* #10: @12 = (@11*@2) */
  w12  = (w11*w2);
  /* #11: @12 = (@10*@12) */
  w12  = (w10*w12);
  /* #12: @13 = 0.5 */
  w13 = 5.0000000000000000e-01;
  /* #13: @14 = input[2][3] */
  w14 = arg[2] ? arg[2][3] : 0;
  /* #14: @15 = (@14*@2) */
  w15  = (w14*w2);
  /* #15: @15 = (@13*@15) */
  w15  = (w13*w15);
  /* #16: @16 = 9.81 */
  w16 = 9.8100000000000005e+00;
  /* #17: @17 = 1.31579 */
  w17 = 1.3157894736842106e+00;
  /* #18: @18 = input[2][0] */
  w18 = arg[2] ? arg[2][0] : 0;
  /* #19: @19 = input[0][5] */
  w19 = arg[0] ? arg[0][5] : 0;
  /* #20: @20 = (@19*@2) */
  w20  = (w19*w2);
  /* #21: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #22: @20 = (@18*@20) */
  w20  = (w18*w20);
  /* #23: @20 = (@17*@20) */
  w20  = (w17*w20);
  /* #24: @20 = (@16*@20) */
  w20  = (w16*w20);
  /* #25: @21 = 9.81 */
  w21 = 9.8100000000000005e+00;
  /* #26: @22 = 1.31579 */
  w22 = 1.3157894736842106e+00;
  /* #27: @23 = input[0][4] */
  w23 = arg[0] ? arg[0][4] : 0;
  /* #28: @2 = (@23*@2) */
  w2  = (w23*w2);
  /* #29: @2 = (-@2) */
  w2 = (- w2 );
  /* #30: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #31: @2 = (@18*@2) */
  w2  = (w18*w2);
  /* #32: @2 = (@22*@2) */
  w2  = (w22*w2);
  /* #33: @2 = (@21*@2) */
  w2  = (w21*w2);
  /* #34: @24 = 00 */
  /* #35: @25 = vertcat(@3, @4, @5, @6, @9, @12, @15, @20, @2, @24) */
  rr=w25;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w9;
  *rr++ = w12;
  *rr++ = w15;
  *rr++ = w20;
  *rr++ = w2;
  /* #36: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<8; ++i) *rr++ = (- *cs++ );
  /* #37: @26 = @25[:8] */
  for (rr=w26, ss=w25+0; ss!=w25+8; ss+=1) *rr++ = *ss;
  /* #38: (@0[0, 1, 2, 6, 9, 12, 15, 19] = @26) */
  for (cii=casadi_s0, rr=w0, ss=w26; cii!=casadi_s0+8; ++cii, ++ss) rr[*cii] = *ss;
  /* #39: @6 = 00 */
  /* #40: @24 = 00 */
  /* #41: @27 = 00 */
  /* #42: @3 = 0.5 */
  w3 = 5.0000000000000000e-01;
  /* #43: @4 = ones(10x1,1nz) */
  w4 = 1.;
  /* #44: {NULL, NULL, NULL, NULL, @5, NULL, NULL, NULL, NULL, NULL} = vertsplit(@4) */
  w5 = w4;
  /* #45: @4 = (@8*@5) */
  w4  = (w8*w5);
  /* #46: @4 = (@3*@4) */
  w4  = (w3*w4);
  /* #47: @4 = (-@4) */
  w4 = (- w4 );
  /* #48: @28 = 00 */
  /* #49: @9 = (@14*@5) */
  w9  = (w14*w5);
  /* #50: @9 = (@10*@9) */
  w9  = (w10*w9);
  /* #51: @9 = (-@9) */
  w9 = (- w9 );
  /* #52: @12 = (@11*@5) */
  w12  = (w11*w5);
  /* #53: @12 = (@13*@12) */
  w12  = (w13*w12);
  /* #54: @15 = input[0][6] */
  w15 = arg[0] ? arg[0][6] : 0;
  /* #55: @20 = (@15*@5) */
  w20  = (w15*w5);
  /* #56: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #57: @20 = (@18*@20) */
  w20  = (w18*w20);
  /* #58: @20 = (@17*@20) */
  w20  = (w17*w20);
  /* #59: @20 = (@16*@20) */
  w20  = (w16*w20);
  /* #60: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #61: @29 = (@2*@5) */
  w29  = (w2*w5);
  /* #62: @29 = (-@29) */
  w29 = (- w29 );
  /* #63: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #64: @29 = (@18*@29) */
  w29  = (w18*w29);
  /* #65: @29 = (@22*@29) */
  w29  = (w22*w29);
  /* #66: @29 = (@21*@29) */
  w29  = (w21*w29);
  /* #67: @30 = 9.81 */
  w30 = 9.8100000000000005e+00;
  /* #68: @31 = 1.31579 */
  w31 = 1.3157894736842106e+00;
  /* #69: @32 = (2.*@5) */
  w32 = (2.* w5 );
  /* #70: @32 = (@23*@32) */
  w32  = (w23*w32);
  /* #71: @33 = (2.*@23) */
  w33 = (2.* w23 );
  /* #72: @5 = (@33*@5) */
  w5  = (w33*w5);
  /* #73: @32 = (@32+@5) */
  w32 += w5;
  /* #74: @32 = (@18*@32) */
  w32  = (w18*w32);
  /* #75: @32 = (@31*@32) */
  w32  = (w31*w32);
  /* #76: @32 = (@30*@32) */
  w32  = (w30*w32);
  /* #77: @32 = (-@32) */
  w32 = (- w32 );
  /* #78: @34 = vertcat(@6, @24, @27, @4, @28, @9, @12, @20, @29, @32) */
  rr=w34;
  *rr++ = w4;
  *rr++ = w9;
  *rr++ = w12;
  *rr++ = w20;
  *rr++ = w29;
  *rr++ = w32;
  /* #79: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<6; ++i) *rr++ = (- *cs++ );
  /* #80: @35 = @34[:6] */
  for (rr=w35, ss=w34+0; ss!=w34+6; ss+=1) *rr++ = *ss;
  /* #81: (@0[3, 10, 13, 16, 20, 23] = @35) */
  for (cii=casadi_s1, rr=w0, ss=w35; cii!=casadi_s1+6; ++cii, ++ss) rr[*cii] = *ss;
  /* #82: @6 = 00 */
  /* #83: @24 = 00 */
  /* #84: @27 = 00 */
  /* #85: @4 = ones(10x1,1nz) */
  w4 = 1.;
  /* #86: {NULL, NULL, NULL, NULL, NULL, @9, NULL, NULL, NULL, NULL} = vertsplit(@4) */
  w9 = w4;
  /* #87: @4 = (@11*@9) */
  w4  = (w11*w9);
  /* #88: @4 = (@3*@4) */
  w4  = (w3*w4);
  /* #89: @4 = (-@4) */
  w4 = (- w4 );
  /* #90: @12 = (@14*@9) */
  w12  = (w14*w9);
  /* #91: @12 = (@7*@12) */
  w12  = (w7*w12);
  /* #92: @28 = 00 */
  /* #93: @20 = (@8*@9) */
  w20  = (w8*w9);
  /* #94: @20 = (@13*@20) */
  w20  = (w13*w20);
  /* #95: @20 = (-@20) */
  w20 = (- w20 );
  /* #96: @29 = (@2*@9) */
  w29  = (w2*w9);
  /* #97: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #98: @29 = (@18*@29) */
  w29  = (w18*w29);
  /* #99: @29 = (@17*@29) */
  w29  = (w17*w29);
  /* #100: @29 = (@16*@29) */
  w29  = (w16*w29);
  /* #101: @32 = (@15*@9) */
  w32  = (w15*w9);
  /* #102: @32 = (2.*@32) */
  w32 = (2.* w32 );
  /* #103: @32 = (@18*@32) */
  w32  = (w18*w32);
  /* #104: @32 = (@22*@32) */
  w32  = (w22*w32);
  /* #105: @32 = (@21*@32) */
  w32  = (w21*w32);
  /* #106: @5 = (2.*@9) */
  w5 = (2.* w9 );
  /* #107: @5 = (@19*@5) */
  w5  = (w19*w5);
  /* #108: @36 = (2.*@19) */
  w36 = (2.* w19 );
  /* #109: @9 = (@36*@9) */
  w9  = (w36*w9);
  /* #110: @5 = (@5+@9) */
  w5 += w9;
  /* #111: @5 = (@18*@5) */
  w5  = (w18*w5);
  /* #112: @31 = (@31*@5) */
  w31 *= w5;
  /* #113: @31 = (@30*@31) */
  w31  = (w30*w31);
  /* #114: @31 = (-@31) */
  w31 = (- w31 );
  /* #115: @35 = vertcat(@6, @24, @27, @4, @12, @28, @20, @29, @32, @31) */
  rr=w35;
  *rr++ = w4;
  *rr++ = w12;
  *rr++ = w20;
  *rr++ = w29;
  *rr++ = w32;
  *rr++ = w31;
  /* #116: @35 = (-@35) */
  for (i=0, rr=w35, cs=w35; i<6; ++i) *rr++ = (- *cs++ );
  /* #117: @34 = @35[:6] */
  for (rr=w34, ss=w35+0; ss!=w35+6; ss+=1) *rr++ = *ss;
  /* #118: (@0[4, 7, 14, 17, 21, 24] = @34) */
  for (cii=casadi_s2, rr=w0, ss=w34; cii!=casadi_s2+6; ++cii, ++ss) rr[*cii] = *ss;
  /* #119: @6 = 00 */
  /* #120: @24 = 00 */
  /* #121: @27 = 00 */
  /* #122: @4 = ones(10x1,1nz) */
  w4 = 1.;
  /* #123: {NULL, NULL, NULL, NULL, NULL, NULL, @12, NULL, NULL, NULL} = vertsplit(@4) */
  w12 = w4;
  /* #124: @14 = (@14*@12) */
  w14 *= w12;
  /* #125: @14 = (@3*@14) */
  w14  = (w3*w14);
  /* #126: @14 = (-@14) */
  w14 = (- w14 );
  /* #127: @11 = (@11*@12) */
  w11 *= w12;
  /* #128: @11 = (@7*@11) */
  w11  = (w7*w11);
  /* #129: @11 = (-@11) */
  w11 = (- w11 );
  /* #130: @8 = (@8*@12) */
  w8 *= w12;
  /* #131: @8 = (@10*@8) */
  w8  = (w10*w8);
  /* #132: @28 = 00 */
  /* #133: @4 = (@23*@12) */
  w4  = (w23*w12);
  /* #134: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #135: @4 = (@18*@4) */
  w4  = (w18*w4);
  /* #136: @17 = (@17*@4) */
  w17 *= w4;
  /* #137: @17 = (@16*@17) */
  w17  = (w16*w17);
  /* #138: @12 = (@19*@12) */
  w12  = (w19*w12);
  /* #139: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #140: @18 = (@18*@12) */
  w18 *= w12;
  /* #141: @22 = (@22*@18) */
  w22 *= w18;
  /* #142: @22 = (@21*@22) */
  w22  = (w21*w22);
  /* #143: @37 = 00 */
  /* #144: @38 = vertcat(@6, @24, @27, @14, @11, @8, @28, @17, @22, @37) */
  rr=w38;
  *rr++ = w14;
  *rr++ = w11;
  *rr++ = w8;
  *rr++ = w17;
  *rr++ = w22;
  /* #145: @38 = (-@38) */
  for (i=0, rr=w38, cs=w38; i<5; ++i) *rr++ = (- *cs++ );
  /* #146: @39 = @38[:5] */
  for (rr=w39, ss=w38+0; ss!=w38+5; ss+=1) *rr++ = *ss;
  /* #147: (@0[5, 8, 11, 18, 22] = @39) */
  for (cii=casadi_s3, rr=w0, ss=w39; cii!=casadi_s3+5; ++cii, ++ss) rr[*cii] = *ss;
  /* #148: @40 = @0' */
  casadi_trans(w0,casadi_s5, w40, casadi_s4, iw);
  /* #149: output[0][0] = @40 */
  casadi_copy(w40, 25, res[0]);
  /* #150: @41 = zeros(10x10,10nz) */
  casadi_clear(w41, 10);
  /* #151: @42 = ones(10x1) */
  casadi_fill(w42, 10, 1.);
  /* #152: (@41[:10] = @42) */
  for (rr=w41+0, ss=w42; rr!=w41+10; rr+=1) *rr = *ss++;
  /* #153: @42 = @41' */
  casadi_trans(w41,casadi_s6, w42, casadi_s6, iw);
  /* #154: output[1][0] = @42 */
  casadi_copy(w42, 10, res[1]);
  /* #155: @43 = zeros(4x10,15nz) */
  casadi_clear(w43, 15);
  /* #156: @6 = 00 */
  /* #157: @24 = 00 */
  /* #158: @27 = 00 */
  /* #159: @44 = ones(4x1,2nz) */
  casadi_fill(w44, 2, 1.);
  /* #160: {@14, @11, NULL, NULL} = vertsplit(@44) */
  w14 = w44[0];
  w11 = w44[1];
  /* #161: @8 = (@23*@11) */
  w8  = (w23*w11);
  /* #162: @8 = (@3*@8) */
  w8  = (w3*w8);
  /* #163: @8 = (-@8) */
  w8 = (- w8 );
  /* #164: @17 = (@2*@11) */
  w17  = (w2*w11);
  /* #165: @17 = (@7*@17) */
  w17  = (w7*w17);
  /* #166: @22 = (@15*@11) */
  w22  = (w15*w11);
  /* #167: @22 = (@10*@22) */
  w22  = (w10*w22);
  /* #168: @11 = (@19*@11) */
  w11  = (w19*w11);
  /* #169: @11 = (@13*@11) */
  w11  = (w13*w11);
  /* #170: @11 = (-@11) */
  w11 = (- w11 );
  /* #171: @18 = 1.31579 */
  w18 = 1.3157894736842106e+00;
  /* #172: @12 = (@2*@19) */
  w12  = (w2*w19);
  /* #173: @4 = (@23*@15) */
  w4  = (w23*w15);
  /* #174: @12 = (@12+@4) */
  w12 += w4;
  /* #175: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #176: @12 = (@12*@14) */
  w12 *= w14;
  /* #177: @18 = (@18*@12) */
  w18 *= w12;
  /* #178: @16 = (@16*@18) */
  w16 *= w18;
  /* #179: @18 = 1.31579 */
  w18 = 1.3157894736842106e+00;
  /* #180: @12 = (@19*@15) */
  w12  = (w19*w15);
  /* #181: @4 = (@2*@23) */
  w4  = (w2*w23);
  /* #182: @12 = (@12-@4) */
  w12 -= w4;
  /* #183: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #184: @12 = (@12*@14) */
  w12 *= w14;
  /* #185: @18 = (@18*@12) */
  w18 *= w12;
  /* #186: @21 = (@21*@18) */
  w21 *= w18;
  /* #187: @18 = 1.31579 */
  w18 = 1.3157894736842106e+00;
  /* #188: @12 = 1 */
  w12 = 1.;
  /* #189: @33 = (@33*@23) */
  w33 *= w23;
  /* #190: @12 = (@12-@33) */
  w12 -= w33;
  /* #191: @36 = (@36*@19) */
  w36 *= w19;
  /* #192: @12 = (@12-@36) */
  w12 -= w36;
  /* #193: @12 = (@12*@14) */
  w12 *= w14;
  /* #194: @18 = (@18*@12) */
  w18 *= w12;
  /* #195: @30 = (@30*@18) */
  w30 *= w18;
  /* #196: @1 = vertcat(@6, @24, @27, @8, @17, @22, @11, @16, @21, @30) */
  rr=w1;
  *rr++ = w8;
  *rr++ = w17;
  *rr++ = w22;
  *rr++ = w11;
  *rr++ = w16;
  *rr++ = w21;
  *rr++ = w30;
  /* #197: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<7; ++i) *rr++ = (- *cs++ );
  /* #198: @45 = @1[:7] */
  for (rr=w45, ss=w1+0; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #199: (@43[0, 3, 6, 9, 12, 13, 14] = @45) */
  for (cii=casadi_s7, rr=w43, ss=w45; cii!=casadi_s7+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #200: @6 = 00 */
  /* #201: @24 = 00 */
  /* #202: @27 = 00 */
  /* #203: @8 = ones(4x1,1nz) */
  w8 = 1.;
  /* #204: {NULL, NULL, @17, NULL} = vertsplit(@8) */
  w17 = w8;
  /* #205: @8 = (@19*@17) */
  w8  = (w19*w17);
  /* #206: @8 = (@3*@8) */
  w8  = (w3*w8);
  /* #207: @8 = (-@8) */
  w8 = (- w8 );
  /* #208: @22 = (@15*@17) */
  w22  = (w15*w17);
  /* #209: @22 = (@7*@22) */
  w22  = (w7*w22);
  /* #210: @22 = (-@22) */
  w22 = (- w22 );
  /* #211: @11 = (@2*@17) */
  w11  = (w2*w17);
  /* #212: @11 = (@10*@11) */
  w11  = (w10*w11);
  /* #213: @17 = (@23*@17) */
  w17  = (w23*w17);
  /* #214: @17 = (@13*@17) */
  w17  = (w13*w17);
  /* #215: @28 = 00 */
  /* #216: @37 = 00 */
  /* #217: @46 = 00 */
  /* #218: @47 = vertcat(@6, @24, @27, @8, @22, @11, @17, @28, @37, @46) */
  rr=w47;
  *rr++ = w8;
  *rr++ = w22;
  *rr++ = w11;
  *rr++ = w17;
  /* #219: @47 = (-@47) */
  for (i=0, rr=w47, cs=w47; i<4; ++i) *rr++ = (- *cs++ );
  /* #220: @48 = @47[:4] */
  for (rr=w48, ss=w47+0; ss!=w47+4; ss+=1) *rr++ = *ss;
  /* #221: (@43[1:13:3] = @48) */
  for (rr=w43+1, ss=w48; rr!=w43+13; rr+=3) *rr = *ss++;
  /* #222: @6 = 00 */
  /* #223: @24 = 00 */
  /* #224: @27 = 00 */
  /* #225: @8 = ones(4x1,1nz) */
  w8 = 1.;
  /* #226: {NULL, NULL, NULL, @22} = vertsplit(@8) */
  w22 = w8;
  /* #227: @15 = (@15*@22) */
  w15 *= w22;
  /* #228: @3 = (@3*@15) */
  w3 *= w15;
  /* #229: @3 = (-@3) */
  w3 = (- w3 );
  /* #230: @19 = (@19*@22) */
  w19 *= w22;
  /* #231: @7 = (@7*@19) */
  w7 *= w19;
  /* #232: @23 = (@23*@22) */
  w23 *= w22;
  /* #233: @10 = (@10*@23) */
  w10 *= w23;
  /* #234: @10 = (-@10) */
  w10 = (- w10 );
  /* #235: @2 = (@2*@22) */
  w2 *= w22;
  /* #236: @13 = (@13*@2) */
  w13 *= w2;
  /* #237: @28 = 00 */
  /* #238: @37 = 00 */
  /* #239: @46 = 00 */
  /* #240: @48 = vertcat(@6, @24, @27, @3, @7, @10, @13, @28, @37, @46) */
  rr=w48;
  *rr++ = w3;
  *rr++ = w7;
  *rr++ = w10;
  *rr++ = w13;
  /* #241: @48 = (-@48) */
  for (i=0, rr=w48, cs=w48; i<4; ++i) *rr++ = (- *cs++ );
  /* #242: @47 = @48[:4] */
  for (rr=w47, ss=w48+0; ss!=w48+4; ss+=1) *rr++ = *ss;
  /* #243: (@43[2:14:3] = @47) */
  for (rr=w43+2, ss=w47; rr!=w43+14; rr+=3) *rr = *ss++;
  /* #244: @49 = @43' */
  casadi_trans(w43,casadi_s9, w49, casadi_s8, iw);
  /* #245: output[2][0] = @49 */
  casadi_copy(w49, 15, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Translational_drone_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Translational_drone_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Translational_drone_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Translational_drone_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Translational_drone_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Translational_drone_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Translational_drone_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void Translational_drone_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Translational_drone_impl_dae_jac_x_xdot_u_z_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Translational_drone_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real Translational_drone_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Translational_drone_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Translational_drone_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Translational_drone_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    case 1: return casadi_s10;
    case 2: return casadi_s11;
    case 3: return casadi_s12;
    case 4: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Translational_drone_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s6;
    case 2: return casadi_s8;
    case 3: return casadi_s13;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Translational_drone_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15;
  if (sz_res) *sz_res = 14;
  if (sz_iw) *sz_iw = 11;
  if (sz_w) *sz_w = 189;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
