/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Translational_drone_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[15] = {14, 1, 0, 11, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};

/* Translational_drone_expl_vde_adj:(i0[10],i1[10],i2[4],i3[])->(o0[14x1,11nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, *w4=w+4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23;
  /* #0: @0 = input[0][5] */
  w0 = arg[0] ? arg[0][5] : 0;
  /* #1: @1 = input[2][0] */
  w1 = arg[2] ? arg[2][0] : 0;
  /* #2: @2 = 1.31579 */
  w2 = 1.3157894736842106e+00;
  /* #3: @3 = 9.81 */
  w3 = 9.8100000000000005e+00;
  /* #4: @4 = input[1][0] */
  casadi_copy(arg[1], 10, w4);
  /* #5: {@5, @6, @7, @8, @9, @10, @11, @12, @13, @14} = vertsplit(@4) */
  w5 = w4[0];
  w6 = w4[1];
  w7 = w4[2];
  w8 = w4[3];
  w9 = w4[4];
  w10 = w4[5];
  w11 = w4[6];
  w12 = w4[7];
  w13 = w4[8];
  w14 = w4[9];
  /* #6: @3 = (@3*@12) */
  w3 *= w12;
  /* #7: @2 = (@2*@3) */
  w2 *= w3;
  /* #8: @3 = (@1*@2) */
  w3  = (w1*w2);
  /* #9: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #10: @12 = (@0*@3) */
  w12  = (w0*w3);
  /* #11: @15 = input[0][4] */
  w15 = arg[0] ? arg[0][4] : 0;
  /* #12: @16 = 1.31579 */
  w16 = 1.3157894736842106e+00;
  /* #13: @17 = 9.81 */
  w17 = 9.8100000000000005e+00;
  /* #14: @17 = (@17*@13) */
  w17 *= w13;
  /* #15: @16 = (@16*@17) */
  w16 *= w17;
  /* #16: @17 = (@1*@16) */
  w17  = (w1*w16);
  /* #17: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #18: @13 = (@15*@17) */
  w13  = (w15*w17);
  /* #19: @12 = (@12-@13) */
  w12 -= w13;
  /* #20: @13 = input[2][3] */
  w13 = arg[2] ? arg[2][3] : 0;
  /* #21: @18 = 0.5 */
  w18 = 5.0000000000000000e-01;
  /* #22: @18 = (@18*@11) */
  w18 *= w11;
  /* #23: @11 = (@13*@18) */
  w11  = (w13*w18);
  /* #24: @12 = (@12+@11) */
  w12 += w11;
  /* #25: @11 = input[2][2] */
  w11 = arg[2] ? arg[2][2] : 0;
  /* #26: @19 = 0.5 */
  w19 = 5.0000000000000000e-01;
  /* #27: @19 = (@19*@10) */
  w19 *= w10;
  /* #28: @10 = (@11*@19) */
  w10  = (w11*w19);
  /* #29: @12 = (@12+@10) */
  w12 += w10;
  /* #30: @10 = input[2][1] */
  w10 = arg[2] ? arg[2][1] : 0;
  /* #31: @20 = 0.5 */
  w20 = 5.0000000000000000e-01;
  /* #32: @20 = (@20*@9) */
  w20 *= w9;
  /* #33: @9 = (@10*@20) */
  w9  = (w10*w20);
  /* #34: @12 = (@12+@9) */
  w12 += w9;
  /* #35: output[0][0] = @12 */
  if (res[0]) res[0][0] = w12;
  /* #36: @12 = 1.31579 */
  w12 = 1.3157894736842106e+00;
  /* #37: @9 = 9.81 */
  w9 = 9.8100000000000005e+00;
  /* #38: @9 = (@9*@14) */
  w9 *= w14;
  /* #39: @12 = (@12*@9) */
  w12 *= w9;
  /* #40: @1 = (@1*@12) */
  w1 *= w12;
  /* #41: @9 = (@15*@1) */
  w9  = (w15*w1);
  /* #42: @9 = (-@9) */
  w9 = (- w9 );
  /* #43: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #44: @14 = (2.*@15) */
  w14 = (2.* w15 );
  /* #45: @21 = (@14*@1) */
  w21  = (w14*w1);
  /* #46: @9 = (@9-@21) */
  w9 -= w21;
  /* #47: @21 = input[0][3] */
  w21 = arg[0] ? arg[0][3] : 0;
  /* #48: @22 = (@21*@17) */
  w22  = (w21*w17);
  /* #49: @9 = (@9-@22) */
  w9 -= w22;
  /* #50: @22 = input[0][6] */
  w22 = arg[0] ? arg[0][6] : 0;
  /* #51: @23 = (@22*@3) */
  w23  = (w22*w3);
  /* #52: @9 = (@9+@23) */
  w9 += w23;
  /* #53: @23 = (@11*@18) */
  w23  = (w11*w18);
  /* #54: @9 = (@9+@23) */
  w9 += w23;
  /* #55: @23 = (@13*@19) */
  w23  = (w13*w19);
  /* #56: @9 = (@9-@23) */
  w9 -= w23;
  /* #57: @23 = 0.5 */
  w23 = 5.0000000000000000e-01;
  /* #58: @23 = (@23*@8) */
  w23 *= w8;
  /* #59: @8 = (@10*@23) */
  w8  = (w10*w23);
  /* #60: @9 = (@9-@8) */
  w9 -= w8;
  /* #61: output[0][1] = @9 */
  if (res[0]) res[0][1] = w9;
  /* #62: @9 = (@0*@1) */
  w9  = (w0*w1);
  /* #63: @9 = (-@9) */
  w9 = (- w9 );
  /* #64: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #65: @8 = (2.*@0) */
  w8 = (2.* w0 );
  /* #66: @1 = (@8*@1) */
  w1  = (w8*w1);
  /* #67: @9 = (@9-@1) */
  w9 -= w1;
  /* #68: @1 = (@22*@17) */
  w1  = (w22*w17);
  /* #69: @9 = (@9+@1) */
  w9 += w1;
  /* #70: @1 = (@21*@3) */
  w1  = (w21*w3);
  /* #71: @9 = (@9+@1) */
  w9 += w1;
  /* #72: @1 = (@10*@18) */
  w1  = (w10*w18);
  /* #73: @9 = (@9-@1) */
  w9 -= w1;
  /* #74: @1 = (@13*@20) */
  w1  = (w13*w20);
  /* #75: @9 = (@9+@1) */
  w9 += w1;
  /* #76: @1 = (@11*@23) */
  w1  = (w11*w23);
  /* #77: @9 = (@9-@1) */
  w9 -= w1;
  /* #78: output[0][2] = @9 */
  if (res[0]) res[0][2] = w9;
  /* #79: @17 = (@0*@17) */
  w17  = (w0*w17);
  /* #80: @3 = (@15*@3) */
  w3  = (w15*w3);
  /* #81: @17 = (@17+@3) */
  w17 += w3;
  /* #82: @10 = (@10*@19) */
  w10 *= w19;
  /* #83: @17 = (@17+@10) */
  w17 += w10;
  /* #84: @11 = (@11*@20) */
  w11 *= w20;
  /* #85: @17 = (@17-@11) */
  w17 -= w11;
  /* #86: @13 = (@13*@23) */
  w13 *= w23;
  /* #87: @17 = (@17-@13) */
  w17 -= w13;
  /* #88: output[0][3] = @17 */
  if (res[0]) res[0][3] = w17;
  /* #89: output[0][4] = @5 */
  if (res[0]) res[0][4] = w5;
  /* #90: output[0][5] = @6 */
  if (res[0]) res[0][5] = w6;
  /* #91: output[0][6] = @7 */
  if (res[0]) res[0][6] = w7;
  /* #92: @7 = 1 */
  w7 = 1.;
  /* #93: @14 = (@14*@15) */
  w14 *= w15;
  /* #94: @7 = (@7-@14) */
  w7 -= w14;
  /* #95: @8 = (@8*@0) */
  w8 *= w0;
  /* #96: @7 = (@7-@8) */
  w7 -= w8;
  /* #97: @7 = (@7*@12) */
  w7 *= w12;
  /* #98: @12 = (@0*@22) */
  w12  = (w0*w22);
  /* #99: @8 = (@21*@15) */
  w8  = (w21*w15);
  /* #100: @12 = (@12-@8) */
  w12 -= w8;
  /* #101: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #102: @12 = (@12*@16) */
  w12 *= w16;
  /* #103: @7 = (@7+@12) */
  w7 += w12;
  /* #104: @12 = (@21*@0) */
  w12  = (w21*w0);
  /* #105: @16 = (@15*@22) */
  w16  = (w15*w22);
  /* #106: @12 = (@12+@16) */
  w12 += w16;
  /* #107: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #108: @12 = (@12*@2) */
  w12 *= w2;
  /* #109: @7 = (@7+@12) */
  w7 += w12;
  /* #110: output[0][7] = @7 */
  if (res[0]) res[0][7] = w7;
  /* #111: @7 = (@22*@19) */
  w7  = (w22*w19);
  /* #112: @12 = (@0*@18) */
  w12  = (w0*w18);
  /* #113: @7 = (@7-@12) */
  w7 -= w12;
  /* #114: @12 = (@21*@20) */
  w12  = (w21*w20);
  /* #115: @7 = (@7+@12) */
  w7 += w12;
  /* #116: @12 = (@15*@23) */
  w12  = (w15*w23);
  /* #117: @7 = (@7-@12) */
  w7 -= w12;
  /* #118: output[0][8] = @7 */
  if (res[0]) res[0][8] = w7;
  /* #119: @7 = (@15*@18) */
  w7  = (w15*w18);
  /* #120: @12 = (@21*@19) */
  w12  = (w21*w19);
  /* #121: @7 = (@7+@12) */
  w7 += w12;
  /* #122: @12 = (@22*@20) */
  w12  = (w22*w20);
  /* #123: @7 = (@7-@12) */
  w7 -= w12;
  /* #124: @12 = (@0*@23) */
  w12  = (w0*w23);
  /* #125: @7 = (@7-@12) */
  w7 -= w12;
  /* #126: output[0][9] = @7 */
  if (res[0]) res[0][9] = w7;
  /* #127: @21 = (@21*@18) */
  w21 *= w18;
  /* #128: @15 = (@15*@19) */
  w15 *= w19;
  /* #129: @21 = (@21-@15) */
  w21 -= w15;
  /* #130: @0 = (@0*@20) */
  w0 *= w20;
  /* #131: @21 = (@21+@0) */
  w21 += w0;
  /* #132: @22 = (@22*@23) */
  w22 *= w23;
  /* #133: @21 = (@21-@22) */
  w21 -= w22;
  /* #134: output[0][10] = @21 */
  if (res[0]) res[0][10] = w21;
  return 0;
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Translational_drone_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Translational_drone_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Translational_drone_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void Translational_drone_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Translational_drone_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Translational_drone_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Translational_drone_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Translational_drone_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Translational_drone_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Translational_drone_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Translational_drone_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 33;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
